apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  #storageClassName: slow
  nfs:
    server: 192.168.3.100
    path: "/nfs"
  persistentVolumeReclaimPolicy: Recycle
