spring:
  application:
    name: admin
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8661/eureka,http://localhost:8662/eureka

---
server:
  port: 8050

---
management:
  security:
    enabled: false