server:
  port: 9000
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8661/eureka,http://localhost:8662/eureka

---
spring:
  application:
    name: payment

---
management:
  security:
    enabled: false