kind: Service
apiVersion: v1
metadata:
  name: demo-maven-repo-service
spec:
  type: NodePort
  selector:
    app: demo-maven-repo
  ports:
    - protocol: TCP
      name: port1
      nodePort: 10081
      port: 8081
      targetPort: 8081
    - protocol: TCP
      name: port2
      nodePort: 10082
      port: 8082
      targetPort: 8082
    - protocol: TCP
      name: port3
      nodePort: 10083
      port: 8083
      targetPort: 8083
