apiVersion: v1
kind: PersistentVolume
metadata:
  name: yd-192-168-0-122-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.0.122
    path: /var/nfs

